#!/usr/bin/env bash
set -e

# WireGuard Admin — Interactive setup
# Generates .env and ansible/inventory.yml from your answers

echo "============================================"
echo "  WireGuard Admin — Setup"
echo "============================================"
echo ""

# Domain / URL
read -rp "Domain name (e.g. vpn.example.com): " DOMAIN
DOMAIN=${DOMAIN:-vpn.example.com}

read -rp "Admin email (for Let's Encrypt + invites): " ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@$DOMAIN}

# WireGuard
read -rp "WireGuard subnet [10.0.0.0/24]: " WG_SUBNET
WG_SUBNET=${WG_SUBNET:-10.0.0.0/24}

read -rp "WireGuard port [51820]: " WG_PORT
WG_PORT=${WG_PORT:-51820}

read -rp "DNS servers for VPN clients [1.1.1.1, 8.8.8.8]: " WG_DNS
WG_DNS=${WG_DNS:-1.1.1.1, 8.8.8.8}

# API
read -rp "API port [8092]: " API_PORT
API_PORT=${API_PORT:-8092}

# SMTP (optional)
echo ""
echo "SMTP settings (for sending invite/activation emails):"
read -rp "SMTP host [localhost]: " SMTP_HOST
SMTP_HOST=${SMTP_HOST:-localhost}

read -rp "SMTP port [25]: " SMTP_PORT
SMTP_PORT=${SMTP_PORT:-25}

read -rp "SMTP from address [noreply@$DOMAIN]: " SMTP_FROM
SMTP_FROM=${SMTP_FROM:-noreply@$DOMAIN}

# HostBill (optional)
echo ""
read -rp "HostBill webhook secret (leave empty to skip): " HB_SECRET
HB_SECRET=${HB_SECRET:-change-me-to-random-secret}

# Database password
DB_PASS=$(openssl rand -hex 16 2>/dev/null || echo "wgadmin")

echo ""
echo "============================================"
echo "  Generating configuration..."
echo "============================================"

# Generate .env
cat > .env << ENVEOF
# Generated by setup.sh — $(date)
DATABASE_URL=postgresql://wgadmin:${DB_PASS}@127.0.0.1:5432/wgadmin

WG_CONFIG_DIR=/etc/wireguard
WG_DEFAULT_DNS=${WG_DNS}
WG_DEFAULT_ENDPOINT=${DOMAIN}
WG_DEFAULT_SUBNET=${WG_SUBNET}
WG_DEFAULT_PORT=${WG_PORT}

HOSTBILL_WEBHOOK_SECRET=${HB_SECRET}

API_PORT=${API_PORT}

SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_FROM=${SMTP_FROM}
BASE_URL=https://${DOMAIN}
ENVEOF
echo "  .env created"

# Generate ansible inventory
cat > ansible/inventory.yml << INVEOF
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_become: true
  vars:
    project_dir: $(pwd)
    domain: ${DOMAIN}
    contact_email: ${ADMIN_EMAIL}
    api_port: ${API_PORT}
    wg_port: ${WG_PORT}
    wg_subnet: "${WG_SUBNET}"
    db_password: "${DB_PASS}"
    smtp_host: "${SMTP_HOST}"
    smtp_port: ${SMTP_PORT}
    smtp_from: "${SMTP_FROM}"
INVEOF
echo "  ansible/inventory.yml created"

# Update docker-compose db password if not default
if [ "$DB_PASS" != "wgadmin" ]; then
  sed -i "s/POSTGRES_PASSWORD: wgadmin/POSTGRES_PASSWORD: ${DB_PASS}/" docker-compose.yml 2>/dev/null || true
fi

echo ""
echo "============================================"
echo "  Setup complete!"
echo "============================================"
echo ""
echo "Next steps:"
echo ""
echo "  1. Install prerequisites (if not already):"
echo "     sudo apt update && sudo apt install -y ansible docker.io docker-compose-plugin git wireguard"
echo "     sudo systemctl enable --now docker"
echo ""
echo "  2. Run the local provisioning playbook:"
echo "     cd ansible && ansible-playbook -i inventory.yml local.yml"
echo ""
echo "  3. (Optional) Set up SSL with Let's Encrypt:"
echo "     cd ansible && ansible-playbook -i inventory.yml certbot.yml"
echo ""
echo "  4. Open https://${DOMAIN}/admin/ui and bootstrap your admin account"
echo ""
