---
- name: Setup WireGuard Admin server
  hosts: all
  become: true
  roles:
    - common
    - docker
    - wireguard
    - nginx
    - role: certbot
      when: ssl_mode | default('local') == 'local'
    - app
